/*
 * Catálogo del álbum "Uruguayos en el espacio".
 * Cada cromo es un asteroide cuyo nombre homenajea a una persona, lugar o proyecto vinculado al Uruguay.
 *
 * Para agregar uno nuevo:
 *   1. Agrega un objeto con un id nuevo (no reutilices ids: el progreso se guarda por id).
 *   2. Guarda su imagen cuadrada (256×256) en img/p<id>.webp.
 *   3. Sube APP_VERSION en js/version.js, cuenta la novedad en APP_NOTES y agrega
 *      las traducciones del cromo en js/i18n.js.
 *
 * Datos orbitales y de descubrimiento: NASA/JPL Small-Body Database (citas oficiales del MPC/WGSBN).
 *   a = semieje mayor (UA) · e = excentricidad · i = inclinación (°) · per = período (días) · D = diámetro (km)
 */
const CATEGORIES = {
    'Especial':    { color: '#FFD45C', icon: 'sparkles' },
    'Astronomía':  { color: '#8FA2FF', icon: 'telescope' },
    'Divulgación': { color: '#34D9C3', icon: 'users' },
    'Ciencia':     { color: '#C9A0FF', icon: 'atom' },
    'Cultura':     { color: '#FF7DB8', icon: 'music' },
    'Educación':   { color: '#FFB547', icon: 'book' },
    'Uruguay':     { color: '#7DD3FC', icon: 'sun' }
};

const commons = file => 'https://commons.wikimedia.org/wiki/File:' + file;


/* Cromo #1: se gana al instalar el álbum en el celular (no tiene código). */
const SPECIAL = {
    id: 1, code: null, install: true, category: 'Especial',
    num: '★', name: 'Uruguayos en el espacio', honoree: 'Cromo de bienvenida',
    desc: 'Entre Marte y Júpiter giran alrededor del Sol más de un millón de asteroides. ' +
          'Cuando la órbita de uno se conoce bien, recibe un número y se le puede proponer un nombre ' +
          'a la Unión Astronómica Internacional. Así, decenas de asteroides llevan nombres de astrónomas y astrónomos, ' +
          'artistas, educadoras, lugares e historia del Uruguay. Este álbum reúne 39 de ellos: ' +
          'busca los códigos misterio en la feria, escríbelos arriba y descubre quién vuela por el espacio.',
    photo: null
};

const CROMOS = [
    SPECIAL,
    { id: 2, code: 'XGQE', num: '5088', name: 'Tancredi', desig: '1979 QZ1', category: 'Astronomía',
      honoree: 'Gonzalo Tancredi', dates: 'n. 1963',
      desc: 'Astrónomo uruguayo especialista en cometas y asteroides, profesor de la Universidad de la República. Su asteroide fue el primero en llevar el nombre de un uruguayo (1993).',
      disc: { date: '1979-08-22', by: ['C.-I. Lagerkvist'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'MBA', a: 3.10, e: 0.157, i: 0.58, per: 2000, D: 15.9 },
      photo: { author: 'BugWarp', license: 'CC BY 4.0', url: commons('Gonzalo_Tancredi_en_diciembre_de_2022_-_BugWarp_(cropped).jpg') } },
    { id: 3, code: 'LCGX', num: '5346', name: 'Benedetti', desig: '1981 QE3', category: 'Cultura',
      honoree: 'Mario Benedetti', dates: '1920–2009',
      desc: 'Escritor y poeta de la Generación del 45, uno de los autores uruguayos más leídos del mundo. Recibió el Premio Reina Sofía de Poesía Iberoamericana (1999). El nombre lo propuso la comunidad del Liceo N.º 58 de Montevideo.',
      disc: { date: '1981-08-24', by: ['H. Debehogne'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'MBA', a: 3.14, e: 0.177, i: 2.45, per: 2040, D: 15.9 }, cite: 'WGSBN Bull. 1, #1',
      photo: { author: 'Elisa Cabot', license: 'CC BY-SA 2.0', url: commons('Mario_Benedetti,_1981.jpg') } },
    { id: 4, code: 'WTQH', num: '5659', name: 'Vergara', desig: '1968 OA1', category: 'Astronomía',
      honoree: 'Gladys Vergara', dates: '1928–2016',
      desc: 'Astrónoma, directora del Observatorio Astronómico de Montevideo y cofundadora de la Asociación de Aficionados a la Astronomía y del Comité Nacional de Astronomía. También cofundó el Comité Antártico Uruguayo.',
      disc: { date: '1968-07-18', by: ['C. Torres', 'S. Cofré'], site: 'Cerro El Roble', cc: 'CL' },
      orbit: { cls: 'MBA', a: 2.33, e: 0.124, i: 6.41, per: 1300 },
      photo: { author: 'Autor desconocido', license: 'CC BY-SA 4.0', url: commons('Gladys_Vergara.jpg') } },
    { id: 5, code: 'WBSQ', num: '5996', name: 'Julioangel', desig: '1983 NR', category: 'Astronomía',
      honoree: 'Julio Ángel Fernández', dates: 'n. 1946',
      desc: 'Astrónomo de la Universidad de la República que estudió cómo evolucionan las órbitas de los cometas. Sus trabajos dieron algunos de los primeros indicios del cinturón transneptuniano y formó a una generación de astrónomos uruguayos.',
      disc: { date: '1983-07-11', by: ['E. Bowell'], site: 'Flagstaff', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.56, e: 0.132, i: 15.5, per: 1500, D: 8.6 }, cite: 'WGSBN Bull. 5, #20',
      photo: { author: 'Javier Licandro', license: 'CC BY-SA 3.0', url: commons('Julio_Ángel_Fernández.jpg') } },
    { id: 6, code: 'NGQP', num: '6252', name: 'Montevideo', desig: '1992 EV11', category: 'Uruguay',
      honoree: 'Ciudad de Montevideo', dates: 'fundada en 1726',
      desc: 'La capital del Uruguay, ciudad natal de Gonzalo Tancredi, uno de sus descubridores. Tiene una larga tradición astronómica: en 1789 se instaló un observatorio para ver un tránsito de Mercurio y en 1955 abrió el primer planetario del mundo hispanohablante.',
      disc: { date: '1992-03-06', by: ['UESAC'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'MBA', a: 2.91, e: 0.062, i: 3.14, per: 1810 }, cite: 'WGSBN Bull. 4, #10',
      photo: { author: 'Eduardo Ruggieri', license: 'CC BY-SA 3.0', url: commons('PALACIO_LEGISLATIVO_01.JPG'), note: 'Palacio Legislativo' } },
    { id: 7, code: 'GUSJ', num: '6380', name: 'Gardel', desig: '1988 CG', category: 'Cultura',
      honoree: 'Carlos Gardel', dates: '1890–1935',
      desc: 'Cantante, compositor y actor, la voz más famosa del tango. Grabó cientos de canciones y compuso con Alfredo Le Pera clásicos como «Volver» y «Por una cabeza». Su lugar de nacimiento (Tacuarembó o Toulouse) todavía se discute.',
      disc: { date: '1988-02-10', by: ['M. Arai', 'H. Mori'], site: 'Yorii', cc: 'JP' },
      orbit: { cls: 'MBA', a: 2.27, e: 0.136, i: 5.37, per: 1250, D: 3.0 },
      photo: { author: 'Autor desconocido', license: 'Dominio público', url: commons('Carlos_gardel_en_su_casa_1933.jpg') } },
    { id: 8, code: 'WZLT', num: '7593', name: 'Cernuschi', desig: '1992 WP4', category: 'Ciencia',
      honoree: 'Félix Cernuschi', dates: '1907–1999',
      desc: 'Físico y astrofísico montevideano que trabajó en Princeton, Harvard y Buenos Aires. En 1955 fundó la primera institución universitaria del Uruguay dedicada a investigar física y astronomía, e impulsó el Planetario de Montevideo.',
      disc: { date: '1992-11-21', by: ['E. F. Helin'], site: 'Palomar', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.56, e: 0.169, i: 14.4, per: 1490, D: 8.6 }, cite: 'WGSBN Bull. 1, #1',
      photo: null },
    { id: 9, code: 'QMLG', num: '9478', name: 'Caldeyro', desig: '2148 P-L', category: 'Ciencia',
      honoree: 'Roberto Caldeyro Barcia', dates: '1921–1996',
      desc: 'Fisiólogo pionero de la perinatología. Con Hermógenes Álvarez creó las «Unidades Montevideo», que miden la intensidad de las contracciones del parto y se usan en todo el mundo. Presidió el PEDECIBA y ayudó a reconstruir la ciencia uruguaya tras la dictadura.',
      disc: { date: '1960-09-24', by: ['C. J. van Houten', 'I. van Houten-Groeneveld', 'T. Gehrels'], site: 'Palomar', cc: 'US' },
      orbit: { cls: 'MBA', a: 3.09, e: 0.141, i: 4.69, per: 1990 }, cite: 'WGSBN Bull. 4, #11',
      photo: { author: 'Jgalonso', license: 'CC BY-SA 4.0', url: commons('Caldeyro.jpg') } },
    { id: 10, code: 'RPCZ', num: '10072', name: 'Uruguay', desig: '1989 GF1', category: 'Uruguay',
      honoree: 'República Oriental del Uruguay', dates: 'independiente desde 1828',
      desc: 'El país, situado al norte del Río de la Plata y al este del río que le da nombre. Habitado por pueblos como los charrúas, fue disputado durante siglos por España y Portugal hasta su independencia en 1828.',
      disc: { date: '1989-04-03', by: ['E. W. Elst'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'MBA', a: 2.28, e: 0.105, i: 3.74, per: 1260 },
      photo: { author: 'Dominio público', license: 'Dominio público', url: commons('Flag_of_Uruguay.svg'), note: 'Bandera nacional' } },
    { id: 11, code: 'GRTU', num: '10476', name: 'Los Molinos', desig: '1981 EY38', category: 'Astronomía',
      honoree: 'Observatorio Astronómico Los Molinos', dates: 'Montevideo',
      desc: 'Observatorio del Ministerio de Educación y Cultura, al norte de Montevideo (código MPC 844). Realiza el seguimiento de asteroides y cometas, y desde allí se descubrieron Vaimaca y Guyunusa, que también están en este álbum.',
      disc: { date: '1981-03-02', by: ['S. J. Bus'], site: 'Siding Spring', cc: 'AU' },
      orbit: { cls: 'MBA', a: 2.32, e: 0.258, i: 9.43, per: 1290, D: 2.9 },
      photo: { author: 'Mike Peel', license: 'CC BY-SA 4.0', url: commons('Los_Molinos_Observatory_2017_018.jpg') } },
    { id: 12, code: 'XMPT', num: '10477', name: 'Lacumparsita', desig: '1981 ET41', category: 'Cultura',
      honoree: 'El tango «La Cumparsita»', dates: 'estrenado en 1917',
      desc: 'El «himno de los tangos», compuesto por el uruguayo Gerardo Matos Rodríguez (1897–1948) y tocado por primera vez en Montevideo en 1917. El nombre celebró su centenario en el congreso internacional de asteroides de 2017, también en Montevideo.',
      disc: { date: '1981-03-02', by: ['S. J. Bus'], site: 'Siding Spring', cc: 'AU' },
      orbit: { cls: 'MBA', a: 2.33, e: 0.134, i: 8.15, per: 1300, D: 3.0 },
      photo: { author: 'Autor desconocido', license: 'Dominio público', url: commons('La_cumparsita_partitur.jpg'), note: 'Tapa de la partitura' } },
    { id: 13, code: 'NWDP', num: '10512', name: 'Yamandu', desig: '1989 TP11', category: 'Divulgación',
      honoree: 'Yamandú Fernández', dates: '1927–2010',
      desc: 'Astrónomo aficionado y comunicador. Construía sus propios telescopios y observaba estrellas variables, ocultaciones, novas y cometas.',
      disc: { date: '1989-10-02', by: ['S. J. Bus'], site: 'Cerro Tololo', cc: 'CL' },
      orbit: { cls: 'MBA', a: 2.42, e: 0.160, i: 3.61, per: 1370, D: 10.0 },
      photo: null },
    { id: 14, code: 'ANPS', num: '10677', name: 'Colucci', desig: '1979 MN3', category: 'Astronomía',
      honoree: 'Adrián Rodríguez Colucci', dates: 'n. 1978',
      desc: 'Astrónomo uruguayo del Observatorio del Valongo, en Río de Janeiro (Brasil). Estudia cómo las mareas cambian las órbitas de planetas y cuerpos menores.',
      disc: { date: '1979-06-25', by: ['E. F. Helin', 'S. J. Bus'], site: 'Siding Spring', cc: 'AU' },
      orbit: { cls: 'MBA', a: 2.27, e: 0.069, i: 1.98, per: 1250, D: 3.6 },
      photo: null },
    { id: 15, code: 'XSGA', num: '10690', name: 'Massera', desig: '1981 DO3', category: 'Ciencia',
      honoree: 'José Luis Massera', dates: '1915–2002',
      desc: 'Matemático que estudió la estabilidad de las ecuaciones diferenciales. El «lema de Massera» permite saber cuándo un equilibrio es estable usando las funciones de Lyapunov.',
      disc: { date: '1981-02-28', by: ['S. J. Bus'], site: 'Siding Spring', cc: 'AU' },
      orbit: { cls: 'OMB', a: 3.20, e: 0.129, i: 6.13, per: 2090, D: 9.2 },
      photo: { author: 'Eduardo Collins', license: 'CC BY-SA 3.0', url: commons('Massera-ec.jpg') } },
    { id: 16, code: 'SMWT', num: '10691', name: 'Sans', desig: '1981 EJ19', category: 'Divulgación',
      honoree: 'Juan Diego Sans', dates: '1922–2005',
      desc: 'Profesor y divulgador de la astronomía en la Universidad de la República. Cofundó la Asociación de Aficionados a la Astronomía y presidió la Sociedad Uruguaya de Astronomía.',
      disc: { date: '1981-03-02', by: ['S. J. Bus'], site: 'Siding Spring', cc: 'AU' },
      orbit: { cls: 'OMB', a: 3.20, e: 0.120, i: 0.67, per: 2090, D: 9.3 },
      photo: null },
    { id: 17, code: 'UMCK', num: '10700', name: 'Juanangelviera', desig: '1981 ET47', category: 'Divulgación',
      honoree: 'Juan Ángel Viera', dates: '1925–2012',
      desc: 'Astrónomo aficionado, profesor de astronomía en secundaria y comunicador. Fue cofundador y presidente honorario de la Asociación de Aficionados a la Astronomía.',
      disc: { date: '1981-03-02', by: ['S. J. Bus'], site: 'Siding Spring', cc: 'AU' },
      orbit: { cls: 'MBA', a: 2.66, e: 0.200, i: 5.19, per: 1590, D: 3.3 },
      photo: null },
    { id: 18, code: 'ZXFL', num: '12648', name: 'Ibarbourou', desig: '1135 T-3', category: 'Cultura',
      honoree: 'Juana de Ibarbourou', dates: '1892–1979',
      desc: '«Juana de América», una de las poetas más populares de Sudamérica. En sus versos los sentimientos se funden con la naturaleza.',
      disc: { date: '1977-10-17', by: ['C. J. van Houten', 'I. van Houten-Groeneveld', 'T. Gehrels'], site: 'Palomar', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.38, e: 0.083, i: 6.2, per: 1340, D: 3.4 },
      photo: { author: 'Elena Bazterrica', license: 'Dominio público', url: commons('Juana_de_Ibarbourou_from_Estampas_de_la_Biblia.jpg') } },
    { id: 19, code: 'LSXD', num: '12823', name: 'Pochintesta', desig: '1997 AP', category: 'Astronomía',
      honoree: 'Alberto Pochintesta', dates: '1909–1984',
      desc: 'Astrónomo del Observatorio de Montevideo y profesor. Fue uno de los descubridores del cometa C/1947 F1 (Rondanina-Bester). El nombre lo propusieron Esmeralda Mallada y W. A. Fröger.',
      disc: { date: '1997-01-02', by: ['T. Kobayashi'], site: 'Oizumi', cc: 'JP' },
      orbit: { cls: 'MBA', a: 2.29, e: 0.168, i: 2.64, per: 1260 },
      photo: null },
    { id: 20, code: 'GKVS', num: '16277', name: 'Mallada', desig: '2000 JW74', category: 'Astronomía',
      honoree: 'Esmeralda Mallada', dates: '1937–2023',
      desc: 'Astrónoma y profesora de la Universidad de la República; estudió cuerpos menores y enseñó cosmografía y matemática. En 1952 fue una de las fundadoras de la Asociación de Aficionados a la Astronomía. Primera astrónoma uruguaya con un asteroide (2015).',
      disc: { date: '2000-05-04', by: ['Spacewatch'], site: 'Kitt Peak', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.76, e: 0.078, i: 8.47, per: 1670, D: 13.3 },
      photo: { author: 'Autor desconocido', license: 'CC BY-SA 4.0', url: commons('Esmeralda_Mallada.jpg') } },
    { id: 21, code: 'CDWE', num: '17179', name: 'Codina', desig: '1999 TC224', category: 'Astronomía',
      honoree: 'Sayd Codina', dates: '1926–2006',
      desc: 'Primer licenciado en Astronomía del Uruguay. Dirigió el Observatorio Nacional de Río de Janeiro (1991–1999), se destacó en instrumentación astronómica y formó a generaciones de astrónomos.',
      disc: { date: '1999-10-04', by: ['LONEOS'], site: 'Anderson Mesa', cc: 'US' },
      orbit: { cls: 'MBA', a: 3.06, e: 0.067, i: 9.03, per: 1960 },
      photo: null },
    { id: 22, code: 'UNHM', num: '17410', name: 'Zitarrosa', desig: '1988 CQ4', category: 'Cultura',
      honoree: 'Alfredo Zitarrosa', dates: '1936–1989',
      desc: 'Cantautor, periodista y poeta, una de las voces más influyentes de la música popular latinoamericana. Muchas de sus canciones hablaron de las luchas por la justicia social. Nombrado en 2023 a petición del Archivo Zitarrosa.',
      disc: { date: '1988-02-13', by: ['E. W. Elst'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'MBA', a: 2.31, e: 0.144, i: 5.64, per: 1280, D: 3.4 }, cite: 'WGSBN Bull. 3, #1',
      photo: { author: 'MartinLore', license: 'CC BY-SA 4.0', url: commons('Zitarrosa-nuevo.jpg'), note: 'Escultura de Zitarrosa' } },
    { id: 23, code: 'BCNZ', num: '17897', name: 'Gallardo', desig: '1999 FV8', category: 'Astronomía',
      honoree: 'Tabaré Gallardo', dates: 'n. 1962',
      desc: 'Astrónomo del Departamento de Astronomía de la Facultad de Ciencias. Estudia la dinámica de cuerpos menores, objetos transneptunianos y planetas extrasolares, en especial las resonancias orbitales.',
      disc: { date: '1999-03-19', by: ['LONEOS'], site: 'Anderson Mesa', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.40, e: 0.128, i: 1.51, per: 1350, D: 2.9 },
      photo: null },
    { id: 24, code: 'GHLN', num: '17919', name: 'Licandro', desig: '1999 GC8', category: 'Astronomía',
      honoree: 'Javier Licandro', dates: 'n. 1966',
      desc: 'Astrónomo uruguayo que estudia las propiedades físicas de asteroides, cometas y objetos transneptunianos. Trabaja en el Instituto de Astrofísica de Canarias (España).',
      disc: { date: '1999-04-09', by: ['LONEOS'], site: 'Anderson Mesa', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.24, e: 0.255, i: 4.93, per: 1220, D: 3.0 },
      photo: null },
    { id: 25, code: 'RNYD', num: '20025', name: 'Petronaviera', desig: '1992 DU7', category: 'Cultura',
      honoree: 'Petrona Viera', dates: '1895–1960',
      desc: 'Pintora sorda, reconocida como la primera pintora profesional del Uruguay y figura del planismo. Su mundo, en silencio, se expresó en obras que hoy son patrimonio del país. El nombre lo impulsaron la inspección de Astronomía de Secundaria y el Centro de Recursos para Sordos.',
      disc: { date: '1992-02-29', by: ['UESAC'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'MBA', a: 2.95, e: 0.089, i: 2.42, per: 1850 }, cite: 'WGSBN Bull. 5, #21',
      photo: { author: 'Archivo de Raquel Pereda', license: 'Dominio público', url: commons('Petrona_viera.jpg') } },
    { id: 26, code: 'EBZM', num: '20054', name: 'Lagrimarios', desig: '1993 FX37', category: 'Cultura',
      honoree: 'Lágrima Ríos', dates: '1924–2006',
      desc: 'Cantante afrouruguaya de candombe y tango que llevó la cultura afrouruguaya a muchos países. Fue la primera presidenta de Mundo Afro y «Mujer del Año» de Montevideo (2002). La propuesta surgió de estudiantes de secundaria.',
      disc: { date: '1993-03-19', by: ['UESAC'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'MBA', a: 2.68, e: 0.081, i: 2.83, per: 1610, D: 4.3 }, cite: 'WGSBN Bull. 4, #14',
      photo: { author: 'Mike Peel', license: 'CC BY-SA 4.0', url: commons('At_Montevideo_2023_484.jpg'), note: 'Su sol en el Paseo de los Soles' } },
    { id: 27, code: 'URFZ', num: '20055', name: 'Mariaespinola', desig: '1993 FB47', category: 'Educación',
      honoree: 'María Espínola', dates: '1878–1963',
      desc: 'Maestra e inspectora que fundó la primera escuela técnica de San José de Mayo. En 1921 integró el Consejo de Enseñanza Primaria y Normal, el cargo más alto ocupado por una mujer en el Uruguay hasta entonces. Escribió «La escuela y el progreso» (1922).',
      disc: { date: '1993-03-19', by: ['UESAC'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'MBA', a: 2.71, e: 0.085, i: 2.33, per: 1630 }, cite: 'WGSBN Bull. 4, #13',
      photo: { author: 'Autor desconocido', license: 'Dominio público', url: commons('María_Espínola.png') } },
    { id: 28, code: 'LXSY', num: '20067', name: 'Marthanieves', desig: '1993 TN24', category: 'Educación',
      honoree: 'Martha Nieves', dates: '1926–2014',
      desc: 'Artista plástica y maestra que trabajó en escuelas y centros de secundaria, rurales y urbanos. Hizo aportes importantes a las artes y la cultura, y recibió el Premio Morosoli de Plata en 2010.',
      disc: { date: '1993-10-09', by: ['E. W. Elst'], site: 'La Silla', cc: 'CL' },
      orbit: { cls: 'OMB', a: 3.21, e: 0.123, i: 1.8, per: 2100, D: 11.0 }, cite: 'WGSBN Bull. 5, #4',
      photo: null },
    { id: 29, code: 'BEWU', num: '20176', name: 'Aliciagoyena', desig: '1996 XK29', category: 'Educación',
      honoree: 'Alicia Goyena', dates: '1897–1977',
      desc: 'Profesora de historia y directora de la Sección Femenina del Instituto Batlle y Ordóñez. Promovió una educación humanista y el acceso de las mujeres a la enseñanza secundaria.',
      disc: { date: '1996-12-13', by: ['Spacewatch'], site: 'Kitt Peak', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.37, e: 0.148, i: 9.26, per: 1330, D: 4.0 }, cite: 'WGSBN Bull. 6, #15',
      photo: { author: 'Julio César Ibarra Warnes', license: 'CC BY-SA 4.0', url: commons('Ilustración_de_Alicia_Goyena.jpg'), note: 'Retrato en acrílico' } },
    { id: 30, code: 'EMVQ', num: '20486', name: 'Lemos', desig: '1999 NU56', category: 'Astronomía',
      honoree: 'Pablo Lemos', dates: 'n. 1990',
      desc: 'Astrónomo que investiga cuerpos menores: las comas de los cometas, las órbitas de los asteroides y cómo evolucionan los planetesimales cuando se forman los planetas. Se doctoró en la TU Braunschweig (Alemania) y trabaja en la Facultad de Ciencias y en educación astronómica.',
      disc: { date: '1999-07-12', by: ['LINEAR'], site: 'Socorro', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.66, e: 0.140, i: 12.1, per: 1590, D: 6.7 }, cite: 'WGSBN Bull. 6, #11',
      photo: null },
    { id: 31, code: 'UQGS', num: '28051', name: 'Bruzzone', desig: '1998 HS153', category: 'Astronomía',
      honoree: 'Juan Sebastián Bruzzone', dates: 'n. 1981',
      desc: 'Estudia meteoros, meteoroides, discos de escombros y sistemas planetarios con radar y observaciones ópticas y polarimétricas. Fue investigador posdoctoral en el Centro Goddard de la NASA y hoy trabaja en la Facultad de Ciencias.',
      disc: { date: '1998-04-25', by: ['LONEOS'], site: 'Anderson Mesa', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.90, e: 0.028, i: 0.97, per: 1800 }, cite: 'WGSBN Bull. 1, #2',
      photo: null },
    { id: 32, code: 'DASV', num: '30449', name: 'Caldas', desig: '2000 NH13', category: 'Astronomía',
      honoree: 'Manuel Caldas', dates: 'n. 1981',
      desc: 'Ingeniero espacial e investigador del Departamento de Astronomía de la Facultad de Ciencias. Trabaja en radioastronomía e instrumentación y participa en BOCOSUR, la red uruguaya de cámaras que detecta bólidos.',
      disc: { date: '2000-07-05', by: ['LONEOS'], site: 'Anderson Mesa', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.83, e: 0.132, i: 10.7, per: 1740 }, cite: 'WGSBN Bull. 3, #9',
      photo: null },
    { id: 33, code: 'DKXE', g: 'f', num: '31418', name: 'Sosaoyarzabal', desig: '1999 AJ34', category: 'Astronomía',
      honoree: 'Andrea Sosa Oyarzabal', dates: 'n. 1968',
      desc: 'Profesora del Centro Universitario Regional del Este (Udelar), donde dirige el observatorio astronómico. Estudia la dinámica y las propiedades físicas de los cuerpos menores del Sistema Solar.',
      disc: { date: '1999-01-14', by: ['LONEOS'], site: 'Anderson Mesa', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.24, e: 0.089, i: 4.12, per: 1230, D: 2.3 }, cite: 'WGSBN Bull. 1, #2',
      photo: null },
    { id: 34, code: 'YHRN', g: 'f', num: '34409', name: 'Venturini', desig: '2000 RB95', category: 'Astronomía',
      honoree: 'Julia Venturini', dates: 'n. 1988',
      desc: 'Astrofísica de la Universidad de Ginebra (Suiza). Crea modelos por computadora de cómo se forman los planetas, incluyendo su estructura interna y cómo migran dentro de su sistema.',
      disc: { date: '2000-09-04', by: ['LONEOS'], site: 'Anderson Mesa', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.97, e: 0.061, i: 9.65, per: 1870, D: 5.2 }, cite: 'WGSBN Bull. 3, #9',
      photo: null },
    { id: 35, code: 'QVRA', num: '34808', name: 'Bocosur', desig: '2001 SY73', category: 'Divulgación',
      honoree: 'Red BOCOSUR (Bólidos del Cono Sur)', dates: 'red de cámaras',
      desc: 'La red uruguaya de cámaras de cielo completo que detecta bólidos. Tiene más de 20 estaciones en azoteas de centros de enseñanza secundaria de todo el país, y docentes y estudiantes ayudan a mantenerla y a analizar los datos.',
      disc: { date: '2001-09-19', by: ['LONEOS'], site: 'Anderson Mesa', cc: 'US' },
      orbit: { cls: 'MBA', a: 3.12, e: 0.037, i: 9.99, per: 2010, D: 5.9 }, cite: 'WGSBN Bull. 3, #9',
      photo: null, avatar: 'meteor' },
    { id: 36, code: 'NBQY', num: '68853', name: 'Vaimaca', desig: '2002 HA9', category: 'Uruguay',
      honoree: 'Vaimaca Pirú', dates: 'm. 1833',
      desc: 'Cacique charrúa que fue soldado de Artigas. En 1833 fue llevado a Francia con otros tres charrúas para ser exhibido; sus restos volvieron al Uruguay en 2002. Este fue el primer asteroide descubierto por un uruguayo desde el Uruguay.',
      disc: { date: '2002-04-19', by: ['BUSCA'], site: 'Los Molinos', cc: 'UY' },
      orbit: { cls: 'MBA', a: 2.68, e: 0.241, i: 12.2, per: 1600, D: 5.7 },
      photo: { author: 'Fisicamartin', license: 'CC BY-SA 4.0', url: commons('Los_últimos_charrúas._Detalle._Vaimaca_Pirú.jpg'), note: 'Monumento «Los últimos charrúas»' } },
    { id: 37, code: 'ZQHT', g: 'f', num: '73342', name: 'Guyunusa', desig: '2002 JX115', category: 'Uruguay',
      honoree: 'Guyunusa', dates: 'm. 1834',
      desc: 'Mujer charrúa llevada a Francia en 1833. Murió en Lyon, con 27 años, un año después de llegar. Su hija, nacida en Francia, quedó al cuidado de Tacuabé, otro de los «últimos charrúas». Este fue el segundo asteroide descubierto por un uruguayo desde el Uruguay.',
      disc: { date: '2002-05-04', by: ['BUSCA'], site: 'Los Molinos', cc: 'UY' },
      orbit: { cls: 'MBA', a: 2.72, e: 0.233, i: 25.3, per: 1640, D: 3.9 },
      photo: { author: 'EVAJADE', license: 'CC BY-SA 3.0', url: commons('Guyunusa_y_Tacuabe.jpg'), note: 'Monumento a Guyunusa y Tacuabé' } },
    { id: 38, code: 'BDRX', num: '168039', name: 'Eefalcoacosta', desig: '2005 LR1', category: 'Astronomía',
      honoree: 'Emilio Eduardo Falco Acosta', dates: 'n. 1954',
      desc: 'Astrónomo uruguayo-estadounidense del Observatorio Astrofísico Smithsonian, retirado en 2020. Publicó más de 580 trabajos sobre lentes gravitacionales, planetas extrasolares y supernovas, y defiende el cielo nocturno de la contaminación lumínica.',
      disc: { date: '2005-06-01', by: ['Mount Lemmon Survey'], site: 'Mount Lemmon', cc: 'US' },
      orbit: { cls: 'OMB', a: 3.45, e: 0.136, i: 8.93, per: 2340, D: 7.1 }, cite: 'WGSBN Bull. 4, #11',
      photo: null },
    { id: 39, code: 'RVTC', num: '434325', name: 'Lautreamont', desig: '2004 JD2', category: 'Cultura',
      honoree: 'Isidore Ducasse, Conde de Lautréamont', dates: '1846–1870',
      desc: 'Poeta francés nacido en Montevideo. Sus «Cantos de Maldoror», oscuros y surrealistas, influyeron en la literatura moderna y anticiparon las vanguardias.',
      disc: { date: '2004-05-11', by: ['Catalina Sky Survey'], site: 'Catalina', cc: 'US' },
      orbit: { cls: 'MBA', a: 3.14, e: 0.375, i: 33.2, per: 2030, D: 3.1 }, cite: 'WGSBN Bull. 5, #28',
      photo: { author: 'Studio Blanchard', license: 'Dominio público', url: commons('Ducasse_Tarbes_(cropped).jpg'), note: 'Presunto retrato, c. 1867' } },
    { id: 40, code: 'QWKG', num: '598719', name: 'Alegalli', desig: '2009 BO64', category: 'Divulgación',
      honoree: 'Alejandro Galli', dates: 'n. 1964',
      desc: 'Astrónomo aficionado que estudia cuerpos menores, lluvias de meteoros y estrellas variables, muy conocido por divulgar la astronomía en Uruguay, Brasil y Argentina. ¡Uno de los descubridores de su asteroide es Javier Licandro, que también está en este álbum!',
      disc: { date: '2009-01-20', by: ['R. Gil-Hutton', 'J. Licandro'], site: 'Kitt Peak', cc: 'US' },
      orbit: { cls: 'MBA', a: 2.70, e: 0.067, i: 6.4, per: 1620 }, cite: 'WGSBN Bull. 5, #10',
      photo: null }
];

/* Fuentes consultadas (se muestran en "Fuentes y créditos"). */
const REFERENCIAS = [
    { title: 'NASA/JPL Small-Body Database: números, descubrimiento, órbitas y citas oficiales de cada asteroide', url: 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html' },
    { title: 'IAU WGSBN Bulletin: boletines oficiales de nombres de cuerpos menores', url: 'https://www.wgsbn-iau.org/files/Bulletins/' },
    { title: 'Minor Planet Center (IAU)', url: 'https://minorplanetcenter.net/' },
    { title: 'El Observador (2021): lista del Observatorio Astronómico de Montevideo de asteroides con nombres uruguayos', url: 'https://www.elobservador.com.uy/nota/cuales-son-los-asteroides-que-llevan-nombres-uruguayos--202162918160' },
    { title: 'El Observador (2023): asteroides Venturini, Caldas y Bocosur', url: 'https://www.elobservador.com.uy/nota/tres-asteroides-tendran-nombres-asociados-a-cientificos-y-proyectos-uruguayos-202362314129' },
    { title: 'El Observador (2023): asteroide Zitarrosa', url: 'https://www.elobservador.com.uy/nota/zitarrosa-al-espacio-un-asteroide-fue-bautizado-en-homenaje-al-cantante-uruguayo-2023117131315' },
    { title: 'Prensa Latina (2024): asteroide Lagrimarios', url: 'https://www.prensa-latina.cu/2024/09/24/nominacion-de-asteroide-rinde-homenaje-a-personalidad-uruguaya/' },
    { title: 'Wikipedia: Petrona Viera', url: 'https://es.wikipedia.org/wiki/Petrona_Viera' },
    { title: 'IAU Office of Astronomy for Education: equipo de Uruguay (Pablo Lemos)', url: 'https://astro4edu.org/naec-network/UY/' },
    { title: 'Departamento de Astronomía, Facultad de Ciencias (Udelar)', url: 'https://astronomia.fcien.edu.uy/integrantes' },
    { title: 'Wikimedia Commons: imágenes de libre uso', url: 'https://commons.wikimedia.org/' }
];
